
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - cd .. && ./bin/run-tests

# Handle git submodules by ourselves.
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules.
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - wget http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.52.tar.gz
  - tar -xvf libmicrohttpd-0.9.52.tar.gz
  - cd libmicrohttpd-0.9.52
  - ./configure && make
  - sudo make install && sudo ldconfig
  - cd .. && sudo rm -rf libmicrohttpd-0.9.52
  - git clone git://github.com/cinemast/libjson-rpc-cpp.git
  - mkdir -p libjson-rpc-cpp/build
  - cd libjson-rpc-cpp/build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DHTTP_CLIENT=YES -DHTTP_SERVER=YES -DCOMPILE_STUBGEN=YES ..
  - make
  - sudo make install && sudo ldconfig

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libboost-all-dev
            - libargtable2-dev
            - libjsoncpp-dev
            - libmicrohttpd-dev
      env: COMPILER=clang++-3.7
